[package]
name = "nanocube2"
version = "0.1.0"
authors = ["Carlos Scheidegger <cscheid@cs.arizona.edu>"]

[dependencies]
rand = "0.3"
timeit = "0.1.2"
rocket = "0.3.3"
rocket_codegen = "0.3.3"

[profile.release]
debug = true
